./lzk.py "hello world hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello what1"
./lzk.py "hello world hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello what1"
./lzk.py "hello world hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello what12"
./lzk.py "hello world hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello what"
./lzk.py "hello world hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello what1"
./lzk.py "hello world hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello what12"
./lzk.py "hello world hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello what123"
./lzk.py "hello world hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello what123 hello"
./lzk.py "hello world hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello what123 hell"
./lzk.py "hello world hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello what123 hello"
./lzk.py "hello world hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello what123 hello1"
./lzk.py "hello world hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello what123 hello113k12;kqew"
